# Generated by Django 4.1.2 on 2022-10-26 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('date_released', models.DateField()),
                ('likes', models.CharField(max_length=100)),
                ('artist_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('artists', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapp.artist')),
            ],
            options={
                'ordering': ['-artist_id'],
            },
        ),
        migrations.CreateModel(
            name='Lyric',
            fields=[
                ('content', models.TextField()),
                ('song_id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('songs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapp.song')),
            ],
        ),
    ]
